Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [2]:
import numpy as np
from numpy import linalg as lg
import random

In [3]:
emp_arr = np.zeros((2,2))
print(emp_arr)

[[0. 0.]
 [0. 0.]]


In [7]:
all_one =np.ones(shape=(4,2))
print(all_one)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
import numpy as np
np.full((2,2), np.inf)
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [8]:
def shape_zero():
    r = np.zeros_like(all_one)
    print(r)
shape_zero()

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
def shape_one():
    one = np.ones_like(all_one)
    print(one)
shape_one()

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
new_list = [1,2,3,4]
arr_convert =np.array(new_list)
print(type(arr_convert))

<class 'numpy.ndarray'>


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.



Create an array with values ranging from 10 to 49. {Hint:np.arrange()}bold text

In [11]:
np.arange(10,49)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.**reshape**

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3X3 identity matrix.{Hint:np.eye()}

In [15]:
identity_matrix = np.eye(3)
print("\n3*3 Identity Matrix:\n", identity_matrix)


3*3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function

In [16]:
random_arr = np.random.randint(10,size=(30))
print(random_arr)
print(np.mean(random_arr))

[3 7 9 0 5 7 6 0 6 5 7 7 7 2 4 5 9 6 7 6 0 3 8 4 6 4 7 3 4 7]
5.133333333333334


Create a 10X10 array with random values and find the minimum and maximum values.

In [18]:
random_arr= np.random.randint(50,size=(10,10))
#print(random_arr)
print(np.min(random_arr))
print(np.max(random_arr))

0
49


Create a zero array of size 10 and replace 5th element with 1.

In [19]:
zeros_num = np.zeros((10))
zeros_num[5] = 1
print(zeros_num)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


Reverse an array arr = [1,2,0,0,4,0].


In [20]:
arr = [1,2,0,0,4,0]
rev_arr = arr[::-1]
print(rev_arr)

[0, 4, 0, 0, 2, 1]


Create a 2d array with 1 on border and 0 inside

In [21]:
import numpy as np

array_one_zero = np.zeros((2, 4), dtype=int)

array_one_zero[:, 0] = 1
array_one_zero[:, -1] = 1

print(array_one_zero)

[[1 0 0 1]
 [1 0 0 1]]


Create a 8X8 matrix and fill it with a checkerboard pattern.

In [26]:
import numpy as np

array_one_zero = np.zeros((8, 8), dtype=int)

for i in array_one_zero:
    print("\n-------------------------------")
    for j in i:
        print(j, end=" | ")
    # print("\n------------------------------")


-------------------------------
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 
-------------------------------
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 
-------------------------------
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 
-------------------------------
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 
-------------------------------
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 
-------------------------------
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 
-------------------------------
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 
-------------------------------
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 

### Array Operations:

In [30]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
w = np.array([11, 12])
v = np.array([9, 10])

# Add
print(np.add(x, y))
print("")

# Subtract the two arrays.
print(np.subtract(x, y))
print("")

# Multiply the array with any integers of your choice.
print(np.multiply(v, 10))
print("")

# Find the square of each element of the array.
print(np.square(w))
print("")

# Find the dot product between: v and w ; x and v ; x and y.
print(np.dot(v, w))
print("")
print(np.dot(x, v))
print("")
print(np.dot(x, y))
print("")


[[ 6  8]
 [10 13]]

[[-4 -4]
 [-4 -3]]

[ 90 100]

[121 144]

219

[29 77]

[[19 22]
 [50 58]]



# Problem - 4: Matrix Operations:

In [32]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [33]:
#Prove A.A−1 = I.
A_Inv = lg.inv(A)
dot_product = np.dot(A,A_Inv)
rounded_dot = np.round(dot_product,decimals=10)
i = [[1,0],[0,1]]
is_equal = i==rounded_dot
print(is_equal)
#proved

[[ True  True]
 [ True  True]]


In [34]:
#Prove AB ̸= BA.
dot_of_AB = np.dot(A,B)
dot_of_BA = np.dot(B,A)
is_equal = dot_of_AB==dot_of_BA
print(is_equal)

[[False False]
 [False False]]


In [35]:
AB_transpose = np.transpose(dot_of_AB)
A_transpose = np.transpose(A)
B_transpose = np.transpose(B)
A_transpose_B = np.dot(B_transpose,A_transpose)
is_equal = AB_transpose==A_transpose_B
print(is_equal)

[[ True  True]
 [ True  True]]


In [36]:
#Solve the following system of Linear equation using Inverse Methods.
A = [[2,-3,1],[1,-1,2],[3,1,-1]]
B = [[-1],[-3],[9]]

#X=A −1⋅B
inv_of_A = lg.inv(A)
X = np.dot(inv_of_A,B)
print("X = ")
print(X)

X = 
[[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
import numpy as np
import time

# Task 1: Element-wise Addition
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.array(list1)
array2 = np.array(list2)

# Using Python lists
start_time = time.time()
result_list_add = [list1[i] + list2[i] for i in range(size)]
time_list_add = time.time() - start_time
print(f"Time for addition with Python lists: {time_list_add:.6f} seconds")

# Using NumPy arrays
start_time = time.time()
result_array_add = array1 + array2
time_array_add = time.time() - start_time
print(f"Time for addition with NumPy arrays: {time_array_add:.6f} seconds")

# Task 2: Element-wise Multiplication
# Using Python lists
start_time = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(size)]
time_list_mul = time.time() - start_time
print(f"Time for multiplication with Python lists: {time_list_mul:.6f} seconds")

# Using NumPy arrays
start_time = time.time()
result_array_mul = array1 * array2
time_array_mul = time.time() - start_time
print(f"Time for multiplication with NumPy arrays: {time_array_mul:.6f} seconds")

# Task 3: Dot Product
# Using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
time_list_dot = time.time() - start_time
print(f"Time for dot product with Python lists: {time_list_dot:.6f} seconds")

# Using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
time_array_dot = time.time() - start_time
print(f"Time for dot product with NumPy arrays: {time_array_dot:.6f} seconds")

# Task 4: Matrix Multiplication
matrix_size = 1000
matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

# Using Python lists
start_time = time.time()
result_matrix_mul = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
time_list_matrix_mul = time.time() - start_time
print(f"Time for matrix multiplication with Python lists: {time_list_matrix_mul:.6f} seconds")

# Using NumPy arrays
start_time = time.time()
result_matrix_mul_np = np.dot(matrix1_np, matrix2_np)
time_array_matrix_mul = time.time() - start_time
print(f"Time for matrix multiplication with NumPy arrays: {time_array_matrix_mul:.6f} seconds")


Time for addition with Python lists: 0.156661 seconds
Time for addition with NumPy arrays: 0.005198 seconds
Time for multiplication with Python lists: 0.236630 seconds
Time for multiplication with NumPy arrays: 0.006201 seconds
Time for dot product with Python lists: 0.277566 seconds
Time for dot product with NumPy arrays: 0.002150 seconds
